import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

let vaultPath = "C:/Dev/Obsidian/Main/.obsidian/plugins/appwrite-obsidian-sync"; // Use forward slashes!

const copyBuildToObsidian = {
	name: "copy-to-obsidian",
	setup(build) {
		build.onEnd((result) => {
			if (result.errors.length > 0) {
				console.error(
					"Build is not copied because the build failed.",
					result.errors,
				);
				return;
			}

			if (!vaultPath.endsWith("/")) {
				vaultPath += "/";
				console.info("added trailing '/' to vaultPath");
			}

			try {
				if (!fs.existsSync(vaultPath)) {
					fs.mkdirSync(vaultPath, { recursive: true });
					console.info(
						`Plugin folder not found, creating "${vaultPath}"`,
					);
				}

				fs.copyFileSync("main.js", path.join(vaultPath, "main.js"));
				fs.copyFileSync(
					"manifest.json",
					path.join(vaultPath, "manifest.json"),
				);

				if (fs.existsSync("styles.css")) {
					fs.copyFileSync(
						"styles.css",
						path.join(vaultPath, "styles.css"),
					);
				}
			} catch (error) {
				console.error("Copy failed", error.message);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyBuildToObsidian],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
